# Import standard packages
from pydantic import BaseModel, Field

# Import custom modules
from .ToolCall import ToolCall

class NPlan(BaseModel):
    """
    Models the plan created by the NAMI worklow's planner node.
    This also acts as the input to the executor.
    """
    input: str = Field(description="The input from the user")
    plan: str = Field(description="The plan generated by the planner agent")
    tool_calls: list[ToolCall] | None = Field(description="The list of tool calls with their arguments to be executed")