# Import standard packages
from pydantic import BaseModel, Field

# Import custom modules
from .NPlan import NPlan
from .NVerdict import NVerdict

class NState(BaseModel):
    """
    Models the shared state in the NAMI graph workflow.
    """
    input: str = Field(description="The input from the user")
    
    # Fields to be populated by the planner
    plan: NPlan | None = Field(description="The plan generated by the planner agent", default=None)
    
    # Fields to be populated by the executor
    verdict: NVerdict | None = Field(description="The final summary generated by the executor", default=None)